// Predefined list of city names for the chat game
export const cities = [
  'Paris',
  'London',
  'Tokyo',
  'New York',
  'Berlin',
  'Rome',
  'Madrid',
  'Amsterdam',
  'Vienna',
  'Prague',
  'Barcelona',
  'Moscow',
  'Istanbul',
  'Dubai',
  'Singapore',
  'Hong Kong',
  'Sydney',
  'Melbourne',
  'Toronto',
  'Vancouver',
  'Los Angeles',
  'Chicago',
  'Miami',
  'San Francisco',
  'Boston',
  'Seattle',
  'Dublin',
  'Edinburgh',
  'Copenhagen',
  'Stockholm',
  'Oslo',
  'Helsinki',
  'Warsaw',
  'Budapest',
  'Bucharest',
  'Athens',
  'Lisbon',
  'Brussels',
  'Zurich',
  'Geneva',
  'Milan',
  'Naples',
  'Florence',
  'Venice',
  'Bangkok',
  'Seoul',
  'Beijing',
  'Shanghai',
  'Mumbai',
  'Delhi',
  'Cairo',
  'Cape Town',
  'Johannesburg',
  'Buenos Aires',
  'Rio de Janeiro',
  'São Paulo',
  'Mexico City',
  'Lima',
  'Santiago',
  'Bogotá',
  'Caracas',
  'Havana',
  'Kingston',
  'Nassau',
  'Reykjavik',
  'Luxembourg',
  'Monaco',
  'Valletta',
  'Nicosia',
  'Belgrade',
  'Zagreb',
  'Ljubljana',
  'Sarajevo',
  'Skopje',
  'Tirana',
  'Riga',
  'Tallinn',
  'Vilnius',
  'Kiev',
  'Minsk',
  'Tbilisi',
  'Yerevan',
  'Baku',
  'Almaty',
  'Tashkent',
  'Manila',
  'Jakarta',
  'Kuala Lumpur',
  'Ho Chi Minh City',
  'Hanoi',
  'Phnom Penh',
  'Vientiane',
  'Yangon',
  'Dhaka',
  'Kathmandu',
  'Colombo',
  'Islamabad',
  'Karachi',
  'Lahore',
  'Tehran',
  'Baghdad',
  'Damascus',
  'Beirut',
  'Amman',
  'Jerusalem',
  'Tel Aviv',
  'Riyadh',
  'Jeddah',
  'Doha',
  'Kuwait City',
  'Manama',
  'Muscat',
  'Sana\'a',
  'Addis Ababa',
  'Nairobi',
  'Dar es Salaam',
  'Kampala',
  'Kigali',
  'Accra',
  'Lagos',
  'Abidjan',
  'Dakar',
  'Casablanca',
  'Tunis',
  'Algiers',
  'Tripoli',
  'Khartoum',
  'Lusaka',
  'Harare',
  'Gaborone',
  'Windhoek',
  'Maputo',
  'Antananarivo',
  'Port Louis',
  'Victoria',
  'Moroni',
  'Djibouti',
  'Asmara',
  'Mogadishu',
  'Banjul',
  'Bissau',
  'Conakry',
  'Freetown',
  'Monrovia',
  'Bamako',
  'Ouagadougou',
  'Niamey',
  'N\'Djamena',
  'Bangui',
  'Brazzaville',
  'Kinshasa',
  'Libreville',
  'Malabo',
  'São Tomé',
  'Luanda',
  'Yaoundé',
  'Douala',
  'Bujumbura',
  'Mbabane',
  'Maseru',
  'Pretoria',
  'Durban',
  'Port Elizabeth',
  'East London',
  'Kimberley',
  'Polokwane',
  'Nelspruit',
  'Upington',
  'George',
  'Oudtshoorn',
  'Mossel Bay',
  'Knysna',
  'Plettenberg Bay',
  'Hermanus',
  'Stellenbosch',
  'Paarl',
  'Franschhoek',
  'Worcester',
  'Robertson',
  'Montagu',
  'Barrydale',
  'Ladismith',
  'Caledon',
  'Swellendam',
  'Riversdale',
  'Still Bay',
  'Witsand',
  'Infanta',
  'Struisbaai',
  'Arniston',
  'Bredasdorp',
  'Napier',
  'Elim',
  'Baardskeerdersbos',
  'Gansbaai',
  'Kleinmond',
  'Betty\'s Bay',
  'Pringle Bay',
  'Rooiels',
  'Gordon\'s Bay',
  'Somerset West',
  'Strand',
  'Macassar',
  'Khayelitsha',
  'Mitchell\'s Plain',
  'Gugulethu',
  'Langa',
  'Nyanga',
  'Crossroads',
  'Philippi',
  'Manenberg',
  'Hanover Park',
  'Athlone',
  'Grassy Park',
  'Ottery',
  'Lansdowne',
  'Claremont',
  'Newlands',
  'Rondebosch',
  'Rosebank',
  'Mowbray',
  'Observatory',
  'Woodstock',
  'Salt River',
  'Maitland',
  'Paarden Eiland',
  'Epping',
  'Goodwood',
  'Parow',
  'Bellville',
  'Durbanville',
  'Kraaifontein',
  'Brackenfell',
  'Kuils River',
  'Blue Downs',
  'Eerste River'
];

// Helper function to get a random city that hasn't been used recently
export const getRandomCity = (recentCities = []) => {
  const availableCities = cities.filter(city => !recentCities.includes(city));
  const cityPool = availableCities.length > 0 ? availableCities : cities;
  const randomIndex = Math.floor(Math.random() * cityPool.length);
  return cityPool[randomIndex];
};
