export const cities = [
  "Athens", "Seoul", "Lima", "Amsterdam", "Munich", "Houston", "Nashville", 
  "Edinburgh", "Hartford", "Denver", "Raleigh", "Helsinki", "Istanbul", "Lyon", 
  "Nantes", "Stockholm", "Moscow", "Warsaw", "Wellington", "Natal", "London", 
  "Naples", "Santiago", "Orlando", "Osaka", "Albany", "York", "Kansas City", 
  "Yuma", "Austin", "Newark", "Kyoto", "Ottawa", "Ankara", "Amarillo", "Oslo", 
  "Omaha", "Alexandria", "Aspen", "Nice", "Eugene", "El Paso", "Odessa", 
  "Atlanta", "Adelaide", "Erie", "Enid", "Dublin", "Nottingham", "Montreal", 
  "Lisbon", "Norfolk", "Krakow", "Wichita", "Abilene", "Evansville", 
  "El Centro", "Oxnard", "Dallas", "Seattle", "Elgin", "Nagoya", "Aberdeen", 
  "Nashua", "Akron", "Norwich", "Hilo", "Oman", "Napa", "Alton", "Norwood", 
  "Detroit", "Troy", "Yonkers", "Salem", "Milan", "Nanjing", "Gary", 
  "Yuba City", "Yakima", "Asheville", "Elkhart", "Tucson", "Nampa", "Augusta", 
  "Ames", "Stockton", "Newton", "Naperville", "Everett", "Tulsa", "Annapolis", 
  "Sumter", "Racine", "Essex", "Xian", "Newburgh", "Heidelberg", "Geneva", 
  "Anaheim", "Mobile", "Eau Claire", "Eureka", "Auburn", "Needham", "Madison", 
  "Natick", "Keene", "Elyria", "Attleboro", "Owensboro", "Olathe", "Encinitas", 
  "Seaside", "Escondido", "Orono", "Oxford", "Dresden", "Norwalk", "Kokomo", 
  "Orange", "Elmira", "Aurora", "Alameda", "Arcadia", "Azusa", "Alhambra", 
  "Antioch", "Hanover", "Rialto", "Oshkosh", "Hayward", "Danbury", "Yerevan", 
  "Norcross", "Scottsdale", "Euclid", "Denton", "Niles", "Savannah", 
  "Honolulu", "Utica", "Andover", "Reno", "Omak", "Kissimmee", "Edmond", 
  "Decatur", "Revere", "Elmwood", "Dedham", "Methuen", "Norristown", 
  "Novato", "Oberlin", "Norco", "Ogden", "Namur", "Roseville", "Enfield", 
  "Dothan", "Natchez", "Zebulon", "Newberg", "Galveston", "Newport", "Tacoma", 
  "Arlington", "Nogales", "Superior", "Renton", "Naples", "Sydney", "Yakutat", 
  "Tehran", "Norman", "Newcastle", "Evanston", "Napier", "Roanoke", "Emporia"
];